# Customer Segmentation & Churn Pattern Analytics in European Banking

## Notebook 01: Data Loading and Validation

### Project Domain
Finance and Banking Analytics

### Project Objective
The purpose of this project is to analyse customer churn patterns in a European bank, identify high-risk customer segments, understand churn differences across demographic and financial profiles, and support data-driven customer-retention strategies.

### Dataset Target
`Exited`

- `Exited = 1`: Customer left the bank
- `Exited = 0`: Customer remained with the bank

In [1]:
# Core data-handling libraries
import pandas as pd
import numpy as np

# Data visualisation libraries
import matplotlib.pyplot as plt

# File and system utilities
from pathlib import Path
import os
import warnings

# Display settings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)
pd.set_option("display.float_format", lambda value: f"{value:,.2f}")

print("Libraries imported successfully.")

Libraries imported successfully.

In [2]:
# Current notebook working directory
current_directory = Path.cwd()

# Determine the project root directory
if current_directory.name.lower() == "notebooks":
    project_root = current_directory.parent
else:
    project_root = current_directory

# Define project folders
data_directory = project_root / "data"
output_directory = project_root / "outputs"
chart_directory = output_directory / "charts"
table_directory = output_directory / "tables"
model_directory = project_root / "models"
report_directory = project_root / "reports"

# Create output folders if they do not already exist
for folder in [
    data_directory,
    output_directory,
    chart_directory,
    table_directory,
    model_directory,
    report_directory
]:
    folder.mkdir(parents=True, exist_ok=True)

print("Current directory :", current_directory)
print("Project root      :", project_root)
print("Data directory    :", data_directory)
print("Chart directory   :", chart_directory)
print("Table directory   :", table_directory)
print("Model directory   :", model_directory)

Current directory : d:\Customer_Segmentation_Churn_Banking\notebooks
Project root      : d:\Customer_Segmentation_Churn_Banking
Data directory    : d:\Customer_Segmentation_Churn_Banking\data
Chart directory   : d:\Customer_Segmentation_Churn_Banking\outputs\charts
Table directory   : d:\Customer_Segmentation_Churn_Banking\outputs\tables
Model directory   : d:\Customer_Segmentation_Churn_Banking\models

In [3]:
# Find all CSV files available in the data directory
csv_files = list(data_directory.glob("*.csv"))

print(f"Number of CSV files found: {len(csv_files)}")

if csv_files:
    print("\nAvailable CSV files:")
    
    for file_number, file_path in enumerate(csv_files, start=1):
        print(f"{file_number}. {file_path.name}")
else:
    print("\nNo CSV file was found.")
    print(f"Place the banking dataset inside: {data_directory}")

Number of CSV files found: 1

Available CSV files:
1. Churn_Modelling.csv

In [4]:
# Preferred dataset filename
preferred_dataset_path = data_directory / "Churn_Modelling.csv"

# Select the appropriate CSV file
if preferred_dataset_path.exists():
    dataset_path = preferred_dataset_path

elif len(csv_files) == 1:
    dataset_path = csv_files[0]

elif len(csv_files) > 1:
    raise FileNotFoundError(
        "Multiple CSV files were found. Rename the required banking dataset "
        "to 'Churn_Modelling.csv'."
    )

else:
    raise FileNotFoundError(
        f"No CSV dataset was found inside the data folder: {data_directory}"
    )

# Load the original dataset
df_raw = pd.read_csv(dataset_path)

# Create a working copy
df = df_raw.copy()

print("Dataset loaded successfully.")
print(f"Dataset file: {dataset_path.name}")
print(f"Number of rows: {df.shape[0]:,}")
print(f"Number of columns: {df.shape[1]:,}")

Dataset loaded successfully.
Dataset file: Churn_Modelling.csv
Number of rows: 10,000
Number of columns: 14

In [5]:
# Display the first five rows
df.head()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,2025,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,"101,348.88",1
1,2025,15647311,Hill,608,Spain,Female,41,1,"83,807.86",1,0,1,"112,542.58",0
2,2025,15619304,Onio,502,France,Female,42,8,"159,660.80",3,1,0,"113,931.57",1
3,2025,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,"93,826.63",0
4,2025,15737888,Mitchell,850,Spain,Female,43,2,"125,510.82",1,1,1,"79,084.10",0

In [6]:
# Display the last five rows
df.tail()

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
9995,2025,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,"96,270.64",0
9996,2025,15569892,Johnstone,516,France,Male,35,10,"57,369.61",1,1,1,"101,699.77",0
9997,2025,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,"42,085.58",1
9998,2025,15682355,Sabbatini,772,Germany,Male,42,3,"75,075.31",2,1,0,"92,888.52",1
9999,2025,15628319,Walker,792,France,Female,28,4,"130,142.79",1,1,0,"38,190.78",0

In [7]:
# Display five randomly selected rows
df.sample(
    n=min(5, len(df)),
    random_state=42
)

,Year,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
6252,2025,15687492,Anderson,596,Germany,Male,32,3,"96,709.07",2,0,0,"41,788.37",0
4684,2025,15736963,Herring,623,France,Male,43,1,0.00,2,1,1,"146,379.30",0
1731,2025,15721730,Amechi,601,Spain,Female,44,4,0.00,2,1,0,"58,561.31",0
4742,2025,15762134,Liang,506,Germany,Male,59,8,"119,152.10",2,1,1,"170,679.74",0
4521,2025,15648898,Chuang,560,Spain,Female,27,7,"124,995.98",1,1,1,"114,669.79",0

In [8]:
print("Dataset dimensions:")
print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]:,}")

print("\nColumn names:")

for column_number, column_name in enumerate(df.columns, start=1):
    print(f"{column_number:02d}. {column_name}")

Dataset dimensions:
Rows    : 10,000
Columns : 14

Column names:
01. Year
02. CustomerId
03. Surname
04. CreditScore
05. Geography
06. Gender
07. Age
08. Tenure
09. Balance
10. NumOfProducts
11. HasCrCard
12. IsActiveMember
13. EstimatedSalary
14. Exited

In [9]:
data_dictionary = pd.DataFrame(
    {
        "Column": [
            "RowNumber",
            "CustomerId",
            "Surname",
            "CreditScore",
            "Geography",
            "Gender",
            "Age",
            "Tenure",
            "Balance",
            "NumOfProducts",
            "HasCrCard",
            "IsActiveMember",
            "EstimatedSalary",
            "Exited"
        ],
        "Description": [
            "Dataset row identifier",
            "Unique customer identifier",
            "Customer surname",
            "Customer creditworthiness score",
            "Customer country: France, Germany or Spain",
            "Customer gender",
            "Customer age in years",
            "Number of years the customer has been with the bank",
            "Customer account balance",
            "Number of banking products used by the customer",
            "Indicates whether the customer owns a credit card",
            "Indicates whether the customer is an active bank member",
            "Estimated annual salary of the customer",
            "Churn target: 1 means exited and 0 means retained"
        ],
        "Variable_Type": [
            "Identifier",
            "Identifier",
            "Text",
            "Numerical",
            "Categorical",
            "Categorical",
            "Numerical",
            "Numerical",
            "Numerical",
            "Numerical",
            "Binary",
            "Binary",
            "Numerical",
            "Binary target"
        ]
    }
)

# Keep only columns that exist in the loaded dataset
data_dictionary = data_dictionary[
    data_dictionary["Column"].isin(df.columns)
].reset_index(drop=True)

data_dictionary

             Column                                        Description  Variable_Type
0        CustomerId                         Unique customer identifier     Identifier
1           Surname                                   Customer surname           Text
2       CreditScore                    Customer creditworthiness score      Numerical
3         Geography         Customer country: France, Germany or Spain    Categorical
4            Gender                                    Customer gender    Categorical
5               Age                              Customer age in years      Numerical
6            Tenure  Number of years the customer has been with the...      Numerical
7           Balance                           Customer account balance      Numerical
8     NumOfProducts    Number of banking products used by the customer      Numerical
9         HasCrCard  Indicates whether the customer owns a credit card         Binary
10   IsActiveMember  Indicates whether the customer is an active ba...         Binary
11  EstimatedSalary            Estimated annual salary of the customer      Numerical
12           Exited  Churn target: 1 means exited and 0 means retained  Binary target

In [10]:
data_dictionary_path = table_directory / "data_dictionary.csv"

data_dictionary.to_csv(
    data_dictionary_path,
    index=False
)

print(f"Data dictionary saved to: {data_dictionary_path}")

Data dictionary saved to: d:\Customer_Segmentation_Churn_Banking\outputs\tables\data_dictionary.csv

In [11]:
print("Dataset information:\n")
df.info()

Dataset information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [12]:
column_summary = pd.DataFrame(
    {
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Non_Null_Count": df.notna().sum().values,
        "Null_Count": df.isna().sum().values,
        "Null_Percentage": (
            df.isna().mean().values * 100
        ).round(2),
        "Unique_Values": df.nunique(dropna=False).values
    }
)

column_summary

             Column Data_Type  Non_Null_Count  Null_Count  Null_Percentage  Unique_Values
0              Year     int64           10000           0             0.00              1
1        CustomerId     int64           10000           0             0.00          10000
2           Surname    object           10000           0             0.00           2932
3       CreditScore     int64           10000           0             0.00            460
4         Geography    object           10000           0             0.00              3
5            Gender    object           10000           0             0.00              2
6               Age     int64           10000           0             0.00             70
7            Tenure     int64           10000           0             0.00             11
8           Balance   float64           10000           0             0.00           6382
9     NumOfProducts     int64           10000           0             0.00              4
10        HasCrCard     int64           10000           0             0.00              2
11   IsActiveMember     int64           10000           0             0.00              2
12  EstimatedSalary   float64           10000           0             0.00           9999
13           Exited     int64           10000           0             0.00              2

In [13]:
column_summary_path = table_directory / "column_summary.csv"

column_summary.to_csv(
    column_summary_path,
    index=False
)

print(f"Column summary saved to: {column_summary_path}")

Column summary saved to: d:\Customer_Segmentation_Churn_Banking\outputs\tables\column_summary.csv

In [14]:
missing_value_summary = pd.DataFrame(
    {
        "Column": df.columns,
        "Missing_Count": df.isna().sum().values,
        "Missing_Percentage": (
            df.isna().mean().values * 100
        ).round(2)
    }
)

missing_value_summary = missing_value_summary.sort_values(
    by="Missing_Count",
    ascending=False
).reset_index(drop=True)

missing_value_summary

             Column  Missing_Count  Missing_Percentage
0              Year              0                0.00
1        CustomerId              0                0.00
2           Surname              0                0.00
3       CreditScore              0                0.00
4         Geography              0                0.00
5            Gender              0                0.00
6               Age              0                0.00
7            Tenure              0                0.00
8           Balance              0                0.00
9     NumOfProducts              0                0.00
10        HasCrCard              0                0.00
11   IsActiveMember              0                0.00
12  EstimatedSalary              0                0.00
13           Exited              0                0.00

In [15]:
total_missing_values = int(df.isna().sum().sum())

if total_missing_values == 0:
    print("Validation passed: No missing values were found.")
else:
    print(
        f"Validation warning: The dataset contains "
        f"{total_missing_values:,} missing values."
    )

Validation passed: No missing values were found.

In [16]:
duplicate_row_count = int(df.duplicated().sum())
duplicate_row_percentage = (
    duplicate_row_count / len(df) * 100
    if len(df) > 0
    else 0
)

print(f"Duplicate rows       : {duplicate_row_count:,}")
print(f"Duplicate percentage : {duplicate_row_percentage:.2f}%")

Duplicate rows       : 0
Duplicate percentage : 0.00%

In [17]:
if "CustomerId" in df.columns:
    duplicate_customer_id_count = int(
        df["CustomerId"].duplicated().sum()
    )

    print(
        f"Duplicate CustomerId values: "
        f"{duplicate_customer_id_count:,}"
    )
else:
    print("CustomerId column was not found.")

Duplicate CustomerId values: 0

In [18]:
numerical_summary = df.describe(
    include=[np.number]
).T

numerical_summary

,count,mean,std,min,25%,50%,75%,max
Year,"10,000.00","2,025.00",0.00,"2,025.00","2,025.00","2,025.00","2,025.00","2,025.00"
CustomerId,"10,000.00","15,690,940.57","71,936.19","15,565,701.00","15,628,528.25","15,690,738.00","15,753,233.75","15,815,690.00"
CreditScore,"10,000.00",650.53,96.65,350.00,584.00,652.00,718.00,850.00
Age,"10,000.00",38.92,10.49,18.00,32.00,37.00,44.00,92.00
Tenure,"10,000.00",5.01,2.89,0.00,3.00,5.00,7.00,10.00
Balance,"10,000.00","76,485.89","62,397.41",0.00,0.00,"97,198.54","127,644.24","250,898.09"
NumOfProducts,"10,000.00",1.53,0.58,1.00,1.00,1.00,2.00,4.00
HasCrCard,"10,000.00",0.71,0.46,0.00,0.00,1.00,1.00,1.00
IsActiveMember,"10,000.00",0.52,0.50,0.00,0.00,1.00,1.00,1.00
EstimatedSalary,"10,000.00","100,090.24","57,510.49",11.58,"51,002.11","100,193.91","149,388.25","199,992.48"
Exited,"10,000.00",0.20,0.40,0.00,0.00,0.00,0.00,1.00

In [19]:
numerical_summary = numerical_summary.rename(
    columns={
        "count": "Count",
        "mean": "Mean",
        "std": "Standard_Deviation",
        "min": "Minimum",
        "25%": "Q1",
        "50%": "Median",
        "75%": "Q3",
        "max": "Maximum"
    }
)

numerical_summary

,Count,Mean,Standard_Deviation,Minimum,Q1,Median,Q3,Maximum
Year,"10,000.00","2,025.00",0.00,"2,025.00","2,025.00","2,025.00","2,025.00","2,025.00"
CustomerId,"10,000.00","15,690,940.57","71,936.19","15,565,701.00","15,628,528.25","15,690,738.00","15,753,233.75","15,815,690.00"
CreditScore,"10,000.00",650.53,96.65,350.00,584.00,652.00,718.00,850.00
Age,"10,000.00",38.92,10.49,18.00,32.00,37.00,44.00,92.00
Tenure,"10,000.00",5.01,2.89,0.00,3.00,5.00,7.00,10.00
Balance,"10,000.00","76,485.89","62,397.41",0.00,0.00,"97,198.54","127,644.24","250,898.09"
NumOfProducts,"10,000.00",1.53,0.58,1.00,1.00,1.00,2.00,4.00
HasCrCard,"10,000.00",0.71,0.46,0.00,0.00,1.00,1.00,1.00
IsActiveMember,"10,000.00",0.52,0.50,0.00,0.00,1.00,1.00,1.00
EstimatedSalary,"10,000.00","100,090.24","57,510.49",11.58,"51,002.11","100,193.91","149,388.25","199,992.48"
Exited,"10,000.00",0.20,0.40,0.00,0.00,0.00,0.00,1.00

In [20]:
numerical_summary_path = (
    table_directory / "numerical_descriptive_statistics.csv"
)

numerical_summary.to_csv(numerical_summary_path)

print(
    f"Numerical summary saved to: "
    f"{numerical_summary_path}"
)

Numerical summary saved to: d:\Customer_Segmentation_Churn_Banking\outputs\tables\numerical_descriptive_statistics.csv

In [21]:
categorical_columns = df.select_dtypes(
    include=["object", "category"]
).columns.tolist()

if categorical_columns:
    categorical_summary = df[
        categorical_columns
    ].describe().T

    categorical_summary
else:
    categorical_summary = pd.DataFrame()
    print("No categorical columns were identified.")

In [22]:
if not categorical_summary.empty:
    categorical_summary_path = (
        table_directory / "categorical_descriptive_statistics.csv"
    )

    categorical_summary.to_csv(categorical_summary_path)

    print(
        f"Categorical summary saved to: "
        f"{categorical_summary_path}"
    )

Categorical summary saved to: d:\Customer_Segmentation_Churn_Banking\outputs\tables\categorical_descriptive_statistics.csv

In [23]:
binary_columns = [
    "HasCrCard",
    "IsActiveMember",
    "Exited"
]

binary_validation_results = []

for column in binary_columns:
    if column in df.columns:
        unique_values = sorted(
            df[column].dropna().unique().tolist()
        )

        valid_binary = set(unique_values).issubset({0, 1})

        binary_validation_results.append(
            {
                "Column": column,
                "Unique_Values": str(unique_values),
                "Valid_Binary_Encoding": valid_binary
            }
        )

binary_validation_df = pd.DataFrame(
    binary_validation_results
)

binary_validation_df

           Column Unique_Values  Valid_Binary_Encoding
0       HasCrCard        [0, 1]                   True
1  IsActiveMember        [0, 1]                   True
2          Exited        [0, 1]                   True

In [24]:
if not binary_validation_df.empty:
    if binary_validation_df[
        "Valid_Binary_Encoding"
    ].all():
        print(
            "Validation passed: All available binary columns "
            "contain only 0 and 1."
        )
    else:
        print(
            "Validation warning: At least one binary column "
            "contains unexpected values."
        )

Validation passed: All available binary columns contain only 0 and 1.

In [25]:
categorical_value_checks = {}

for column in ["Geography", "Gender"]:
    if column in df.columns:
        categorical_value_checks[column] = (
            df[column]
            .value_counts(dropna=False)
            .sort_index()
        )

for column, counts in categorical_value_checks.items():
    print(f"\nValue counts for {column}:")
    print(counts)

Value counts for Geography:
Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

Value counts for Gender:
Gender
Female    4543
Male      5457
Name: count, dtype: int64

In [26]:
target_column = "Exited"

if target_column not in df.columns:
    raise KeyError(
        f"The required target column '{target_column}' "
        "was not found in the dataset."
    )

target_counts = (
    df[target_column]
    .value_counts(dropna=False)
    .sort_index()
)

target_percentages = (
    df[target_column]
    .value_counts(
        normalize=True,
        dropna=False
    )
    .sort_index()
    .mul(100)
    .round(2)
)

target_distribution = pd.DataFrame(
    {
        "Customer_Count": target_counts,
        "Percentage": target_percentages
    }
)

target_distribution.index.name = "Exited"
target_distribution

        Customer_Count  Percentage
Exited
0                 7963       79.63
1                 2037       20.37

In [27]:
total_customers = len(df)
retained_customers = int((df["Exited"] == 0).sum())
churned_customers = int((df["Exited"] == 1).sum())
overall_churn_rate = df["Exited"].mean() * 100

print(f"Total customers    : {total_customers:,}")
print(f"Retained customers : {retained_customers:,}")
print(f"Churned customers  : {churned_customers:,}")
print(f"Overall churn rate : {overall_churn_rate:.2f}%")

Total customers    : 10,000
Retained customers : 7,963
Churned customers  : 2,037
Overall churn rate : 20.37%

In [28]:
numerical_validation_rules = {
    "CreditScore": (0, 1000),
    "Age": (18, 120),
    "Tenure": (0, None),
    "Balance": (0, None),
    "NumOfProducts": (0, None),
    "EstimatedSalary": (0, None)
}

numerical_validation_results = []

for column, limits in numerical_validation_rules.items():
    if column in df.columns:
        minimum_allowed, maximum_allowed = limits

        invalid_low_count = int(
            (df[column] < minimum_allowed).sum()
        )

        if maximum_allowed is not None:
            invalid_high_count = int(
                (df[column] > maximum_allowed).sum()
            )
        else:
            invalid_high_count = 0

        numerical_validation_results.append(
            {
                "Column": column,
                "Minimum_Observed": df[column].min(),
                "Maximum_Observed": df[column].max(),
                "Invalid_Below_Minimum": invalid_low_count,
                "Invalid_Above_Maximum": invalid_high_count
            }
        )

numerical_validation_df = pd.DataFrame(
    numerical_validation_results
)

numerical_validation_df

            Column  Minimum_Observed  Maximum_Observed  Invalid_Below_Minimum  Invalid_Above_Maximum
0      CreditScore            350.00            850.00                      0                      0
1              Age             18.00             92.00                      0                      0
2           Tenure              0.00             10.00                      0                      0
3          Balance              0.00        250,898.09                      0                      0
4    NumOfProducts              1.00              4.00                      0                      0
5  EstimatedSalary             11.58        199,992.48                      0                      0

In [29]:
validation_report = pd.DataFrame(
    {
        "Validation_Check": [
            "Dataset loaded",
            "Dataset contains records",
            "Target column available",
            "Missing values",
            "Duplicate rows",
            "Duplicate customer IDs",
            "Valid target encoding"
        ],
        "Result": [
            True,
            len(df) > 0,
            "Exited" in df.columns,
            total_missing_values == 0,
            duplicate_row_count == 0,
            (
                duplicate_customer_id_count == 0
                if "CustomerId" in df.columns
                else None
            ),
            (
                set(df["Exited"].dropna().unique())
                .issubset({0, 1})
                if "Exited" in df.columns
                else False
            )
        ],
        "Details": [
            dataset_path.name,
            f"{len(df):,} records",
            "Exited" if "Exited" in df.columns else "Not found",
            f"{total_missing_values:,} missing values",
            f"{duplicate_row_count:,} duplicate rows",
            (
                f"{duplicate_customer_id_count:,} duplicate IDs"
                if "CustomerId" in df.columns
                else "CustomerId not available"
            ),
            (
                str(sorted(df["Exited"].dropna().unique().tolist()))
                if "Exited" in df.columns
                else "Target unavailable"
            )
        ]
    }
)

validation_report

           Validation_Check  Result              Details
0            Dataset loaded    True  Churn_Modelling.csv
1  Dataset contains records    True       10,000 records
2   Target column available    True               Exited
3            Missing values    True     0 missing values
4            Duplicate rows    True     0 duplicate rows
5    Duplicate customer IDs    True      0 duplicate IDs
6     Valid target encoding    True               [0, 1]

In [30]:
validation_report_path = (
    table_directory / "initial_validation_report.csv"
)

validation_report.to_csv(
    validation_report_path,
    index=False
)

print(
    f"Validation report saved to: "
    f"{validation_report_path}"
)

Validation report saved to: d:\Customer_Segmentation_Churn_Banking\outputs\tables\initial_validation_report.csv

## Initial Dataset Findings

- The dataset contains **_____ customer records** and **_____ columns**.
- The target variable is `Exited`.
- `Exited = 1` represents customers who left the bank.
- `Exited = 0` represents customers who remained with the bank.
- The dataset contains **_____ missing values**.
- The dataset contains **_____ duplicate rows**.
- The dataset contains **_____ duplicate CustomerId values**.
- The overall customer churn rate is **_____ %**.
- The available countries are **_____**.
- The available gender categories are **_____**.
- Binary fields were checked for consistent `0` and `1` encoding.
- Numerical columns were checked for impossible or invalid values.